export const dummyData = [
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "1234",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 100,
      Ahorro_Potencial: 231,
    },
    {
      ID: "2345",
      Ciudad: "Barcelona",
      Tipologia: "Simple",
      Comunicacion: "",
      Pasarela_Clima: "",
      Alumbrado: "",
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: 3,
      Impacto_Anomalías: 2,
      Detected_Score: 50,
      Ahorro_Potencial: 231,
    },
    {
      ID: "4567",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: true,
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: "",
      Impacto_Anomalías: 2,
      Detected_Score: 2,
      Ahorro_Potencial: 231,
    },
    {
      ID: "4567",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: true,
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: "",
      Impacto_Anomalías: 2,
      Detected_Score: 2,
      Ahorro_Potencial: 231,
    },
    {
      ID: "4567",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: true,
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: "",
      Impacto_Anomalías: 2,
      Detected_Score: 2,
      Ahorro_Potencial: 231,
    },
    {
      ID: "4567",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: true,
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: "",
      Impacto_Anomalías: 2,
      Detected_Score: 2,
      Ahorro_Potencial: 231,
    },
    {
      ID: "4567",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: true,
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: "",
      Impacto_Anomalías: 2,
      Detected_Score: 2,
      Ahorro_Potencial: 231,
    },
    {
      ID: "4567",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: true,
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: "",
      Impacto_Anomalías: 2,
      Detected_Score: 2,
      Ahorro_Potencial: 231,
    },
    {
      ID: "4567",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: true,
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: "",
      Impacto_Anomalías: 2,
      Detected_Score: 2,
      Ahorro_Potencial: 231,
    },
    {
      ID: "4567",
      Ciudad: "Barcelona",
      Tipologia: "Completa",
      Comunicacion: "",
      Pasarela_Clima: false,
      Alumbrado: true,
      Clima: "",
      Banderola: "",
      Rotulo: "",
      Consumo_Clima: "",
      Confort: "",
      Anomalías: "",
      Impacto_Anomalías: 2,
      Detected_Score: 2,
      Ahorro_Potencial: 231,
    },
  ]